### ISSUE TITLE
Backend Development - 1

### ISSUE THREAD

**Issue by thelastmattstanding** [ChatSam/Weapons_detection_immich#5]
### **Tasks**

- [x] Explore the different microservices available.
- [x] Understand how to retrieve video stores in Immich and have it redirected to the ML container.
- [x] Create a dummy REST API endpoint in NodeJS for the front end to interact.
- [x] #13

**Comment by thelastmattstanding** [comment]
First task was completed. 
Remaining tasks will be done in parallel with MVP creation since Immich codebase can take time to understand.

**Comment by thelastmattstanding** [comment]
I've looked into Immich codebase and understood a lot of the flows in data. This is still in progress

**Comment by thelastmattstanding** [comment]
A new microservice won't be required so I'm removing that requirement after exploring the codebase more. We will instead introduce a few new Data Transfer Objects within the Immich-server microservice and define how they interact with the ML model and frontend.

**Comment by thelastmattstanding** [comment]
Rather than download and redirect videos, it's better to take an approach similar to how images are processed currently in Immich for their ML models. Further collaboration is required and decisions need to be made on how video objects will be passed to the ML model. Closing Task for now.
